name: quitmate
description: A Flutter app to help users quit smoking with progress tracking and motivation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6
  
  # State Management
  provider: ^6.1.1
  
  # Localization
  easy_localization: ^3.0.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Charts
  fl_chart: ^0.65.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Date/Time
  intl: ^0.18.1
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/localization/
    - assets/images/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700 